POST http://13.235.253.162:8082/v1/auth/register
Content-Type: application/json

{
    "name": "a-users",
    "email": "akrishakundn-users@gmail.com",
    "password": "auser123"
}

###
POST http://13.235.253.162:8082/v1/auth/login
Content-Type: application/json

{
    "email": "akrishakundn-users@gmail.com",
    "password": "auser123"
}

###
GET http://13.235.253.162:8082/v1/users/63c00e19d10a6914f3abfff0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MwMTRjNjdjZDZhNDI2ZTQ0MTU1YzkiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczNTQ3MDg3LCJpYXQiOjE2NzM1MzI2ODcuODJ9.BRCei39giPn8icA3LxaU58s_ISncxnXXCUZjeGxPgck

###
GET http://13.235.253.162:8082/v1/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MwMTRjNjdjZDZhNDI2ZTQ0MTU1YzkiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczNTQ3MDg3LCJpYXQiOjE2NzM1MzI2ODcuODJ9.BRCei39giPn8icA3LxaU58s_ISncxnXXCUZjeGxPgck

###
PUT http://43.204.172.19:8082/v1/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JlN2Y0ZWIzYjJjMTFhMmY1ZTVmYjciLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczNDQzMjIxLCJpYXQiOjE2NzM0Mjg4MjEuMDAxfQ.Y-hiJKoXtLj6S-7qQzL9sOW3m3qxepgEMUCxgLBZzdE
Content-Type: application/json

{
    "productId": "6005913ffaa2bffe60466952",
    "quantity": 0
}

###
POST http://43.204.172.19:8082/v1/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JlN2Y0ZWIzYjJjMTFhMmY1ZTVmYjciLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjczNDQzMjIxLCJpYXQiOjE2NzM0Mjg4MjEuMDAxfQ.Y-hiJKoXtLj6S-7qQzL9sOW3m3qxepgEMUCxgLBZzdE
Content-Type: application/json

{
    "productId": "6005913ffaa2bffe60466952",
    "quantity": 10
}